DFE-Digital/login.dfe.directories

- README.md
- src/api/changePassword.js
- src/api/index.js
Change url for change password, check params and body, also change to the documentation to reflect this
> Change to url for change password

- src/api/find.js
- src/api/index.js
Change made so that find will work via id or by email - open for discussion!
> Change to find API call

- .eslintrc
- src/api/find.js
- src/user/UserRedisAdapter.js
- test/usertests/UserRedisAdapter.test.js
Change to user redis adapter, find by id will also check find by username as well
> Nsa 28 reset password

- src/app/invitations/api/index.js
- src/app/user/api/index.js
> NSA 658 view my services

- src/app/userCodes/api/putUpsertCode.js
- test/userCodesTests/putUpsertCode.test.js
Add client id that is passed in the body and validated, to the creation of the password reset code email
> NSA-631 Add client to create email

- src/app/user/adapter/UserRedisAdapter.js
- src/app/user/api/list.js
Changed to use scan instead of keys for the ioredis adapter.
> Change to use scan instead of keys for redis

- src/app/dev/index.js
- src/index.js
* Reorder imports to get AI logs
* Remove hard reference to User Codes redis store
> Azure Sequelize issue

- azure/infparameters.json
- azure/inftemplate.json
> Updated inf arm templates

- package-lock.json
- package.json
- src/app/invitations/api/postInvitations.js
- src/app/invitations/utils/index.js
- test/invitationsTests/postInvitation.test.js
* Generate code for invitation
* Include code in email
> NSA-969 - Add code to invitation

- azure/infparameters.json
Value defaults to on but can be controlled with release
> Tokenized TDE option

- azure/parameters.json
- azure/template.json
> Updated ARM template

- src/app/userCodes/api/putUpsertCode.js
- src/app/userCodes/data/sequelizeUserCodeStorage.js
Check email correctly to determine whether to regenerate the code
> NSA-1100 - Set uid correctly for update

- src/app/invitations/api/index.js
- src/app/invitations/api/postInvitations.js
- src/app/invitations/api/postResendInvitation.js
- src/app/invitations/utils/sendInvitation.js
Allow resending of invitation email from support console
> NSA-1455- Support resend invitation

- src/app/invitations/api/postResendInvitation.js
> NSA-1455- resent invitation

- package-lock.json
- package.json
update tedious version to fix deprecated tls calls error
> Updated tedious version

- azure/parameters.json
- azure/template.json
Added params for cert and hostname
> Updated templates

- package.json
- src/infrastructure/logger/index.js
> [NSA-2199] Update Application Insights to v1.3.1

- Dockerfile
- azure/template.json
- package-lock.json
- package.json
- src/infrastructure/logger/index.js
Upgraded default node version to Node 10.16 (LTS) and bumped a few package dependencies to fix some vulns
> NSA-1571 - Node 10 upgrade

- config/login.dfe.directories.dev.json
- package-lock.json
- package.json
Node engine - node 8 to 10 upgrade
sequelize - upgrade ver from 4.38.0 to v 4.44.3
> Nsa 1571 node10 migrate

- src/app/dev/index.js
- src/app/devices/data/sequelize.js
- src/app/invitations/data/sequelizeInvitationStorage.js
- src/app/user/adapter/UserSequelizeAdapter.js
- src/app/userCodes/data/sequelizeUserCodeStorage.js
This reverts commit dadf40d26bbbf9431bf7591f7689d9eaefea1db5.
> Revert "Feature/nsa 3915 2 (#231)"

- package-lock.json
- package.json
- src/app/invitations/utils/sendInvitation.js
- src/app/userCodes/api/putUpsertCode.js
- src/app/userCodes/data/redisUserCodeStorage.js
More logging for warning and errors has been added
> PR-feature/4831-Add-logging-when-sending-an-email(directories)

- src/app/user/adapter/UserFileAdapter.js
- src/app/user/adapter/UserRedisAdapter.js
- src/app/user/adapter/UserSequelizeAdapter.js
- test/usertests/UserRedisAdapter.test.js
Avinash reverted changes related to ticket DSI-5037 in order to separate the tickets for release
> Revert "Feature/dsi 5037 increase crypto iterations"

- src/app/user/adapter/UserSequelizeAdapter.js
had to remove prev_login from user update as was causing issues with regression tests
> remove update addition

- src/app/user/adapter/UserSequelizeAdapter.js
fixed the no policy code to allow no policy code user to change password
> fix chnaged password

- DevOps/templates/template.json
https://dfe-secureaccess.atlassian.net/browse/DSI-6574
- Add/update audit logging to the directories component via azure service bus
> add service bus connection

- src/app/user/adapter/UserSequelizeAdapter.js
hot fix to fix change password and reset password is matched and policy code collection
[hotsfix](https://dfe-secureaccess.atlassian.net/jira/software/c/projects/DSI/boards/14?selectedIssue=DSI-6606)
> fix to reset and change password

- src/app/user/api/createUser.js
- test/usertests/createUser.test.js
Jira ticket: [https://dfe-secureaccess.atlassian.net/browse/DSI-7191]( https://dfe-secureaccess.atlassian.net/browse/DSI-7191)
- updated parameter validation when calling the API i.e. either password or entraOid
- validate that the provided entraOid hasn't already been assigned to a user
- update and provide additional unit tests
> [DSI 7191] Amend the create user api to support entra

- src/app/user/api/helpers.js
- test/usertests/helpers.test.js
Part of Jira ticket: [https://dfe-secureaccess.atlassian.net/browse/DSI-7212](https://dfe-secureaccess.atlassian.net/browse/DSI-7212) 
- Update isUuid to be case insensitive
- Write additional unit tests
> [DSI 7212] Update isUuid to be case insensitive

- src/app/user/adapter/UserAzureActiveDirectoryAdapter.js
- src/app/user/adapter/UserRedisAdapter.js
- src/app/user/adapter/UserSequelizeAdapter.js
- src/app/user/api/index.js
- src/app/user/api/updateUserLastLogin.js
- test/usertests/adapter/userSequelizeAdapter/updateUserLastLogin.test.js
- test/usertests/updateUserLastLogin.test.js
Jira ticket: [DSI-7272](https://dfe-secureaccess.atlassian.net/browse/DSI-7272)
- Refactor `UserSequelizeAdapter.js` and add a `updateLastLogin`
- Call `updateLastLogin` during a successful login within `authenticate` 
- Add API endpoint for `updateLastLogin`
- Add additional unit tests
> [DSI-7272] Update last_login for entra linked users

- package-lock.json
Jira ticket: https://dfe-secureaccess.atlassian.net/browse/DSI-7476
- Resolved all npm vulnerabilities with `npm audit fix`
> [DSI-7476] Fix npm vulnerabilities

- src/app/invitations/api/patchInvitation.js
- test/invitationsTests/patchInvitation.test.js
Link to ticket: [NSA-8779](https://dfe-secureaccess.atlassian.net/browse/NSA-8779)
> [NSA-8779] Allow modification of the name of an invited user

- package-lock.json
- package.json
Jira ticket: https://dfe-secureaccess.atlassian.net/browse/DSI-7499
- Update `login.dfe.api.auth` to use version package ^2.3.4
- Fix 1 moderate severity vulnerability using `npm audit fix`
- https://github.com/DFE-Digital/login.dfe.api.auth/pull/29
> [DSI-7499] Update dfe package

- package-lock.json
- package.json
Jira ticket: 
- https://dfe-secureaccess.atlassian.net/browse/DSI-7500
- https://dfe-secureaccess.atlassian.net/browse/DSI-7501
- Update `login.dfe.audit.transporter` to use version package ^4.0.3
- Update `login.dfe.audit.winston-sequelize-transport` to use version package ^3.2.6
- https://github.com/DFE-Digital/login.dfe.audit-transporter/pull/32
- https://github.com/DFE-Digital/login.dfe.audit.winston-sequelize-transport/pull/48
> [DSI-7500, DSI-7501] Update various dfe package

- package-lock.json
- package.json
Ensure that email addresses are transformed to lower case when using Graph API.
> [DSI-7708] Update to use v1.0.17 of 'login.dfe.entra-auth-extensions'
